# Site
name: "CS Society"
title: "CS Society"
description: "The official CS Society of Ashoka University"
logo: 'assets/images/cssoc.png'
favicon: 'assets/images/cssoc-icon.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  soham:
    name: Soham De
    display_name: Soham De
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: 'assets/images/soham.png'
    email: soham.de_ug22@ashoka.edu.in
    web: https://www.sohamde.in
    twitter: https://twitter.com/actuallysoham
    description: "CS Undergrad @ Ashoka"
  tanvi:
    name: Tanvi Roy
    display_name: Tanvi Roy    
    avatar: 'assets/images/tanvi.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: tanvi.roy_ug22@ashoka.edu.in
    web: https://www.tanviroy.com
    description: "CS Undergrad @ Ashoka"
  bagchi:
    name: Soham Bagchi 
    display_name: Soham Bagchi    
    avatar: 'assets/images/bagchi.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: tanvi.roy_ug22@ashoka.edu.in
    web: https://www.tanviroy.com
    description: "CS Undergrad @ Ashoka"
  manish:
    name: Manish Rajani 
    display_name: Manish Rajani     
    avatar: 'assets/images/manish.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: tanvi.roy_ug22@ashoka.edu.in
    web: https://www.tanviroy.com
    description: "CS Undergrad @ Ashoka"
  akshat:
    name: Akshat Singh 
    display_name: Akshat Singh     
    avatar: 'assets/images/akshat.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: tanvi.roy_ug22@ashoka.edu.in
    web: https://www.tanviroy.com
    description: "CS Undergrad @ Ashoka"
  vibodh:
    name: Vibodh Nautiyal 
    display_name: Vibodh Nautiyal     
    avatar: 'assets/images/vibodh.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: tanvi.roy_ug22@ashoka.edu.in
    web: https://www.tanviroy.com
    description: "CS Undergrad @ Ashoka"
  admin:
    name: CS Society
    display_name: CS Society
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: 'assets/images/logo.png'
    email: cs.society@ashoka.edu.in
    web: https://www.cs-ashoka.github.io
    description: "Admin"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
